# Location of top-level MicroPython directory
MPY_DIR = $(HOME)/git/micropython

# Name of module
MOD = eve

# Source files (.c or .py)
SRC = stem.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
